[theme]
#theme = "nord-dark"
#theme = "slick"
theme = "semi-native"
[icons]
icons = "awesome4"

# Documentation: https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html

[[block]]
block = "uptime"

#[[block]]
#block = "docker"
#format = " $icon $running.eng(w:1)/$total "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $percentage free "
format_alt = " $icon $available/$total free "
[[block.click]]
button = "right"
cmd = "baobab /"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available/$total free "
format_alt = " $icon $percentage free "
icons_format = ""
[[block.click]]
button = "right"
cmd = "baobab /home"

[[block]]
block = "memory"
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
[[block.click]]
button = "right"
cmd = "gnome-system-monitor"

[[block]]
block = "cpu"
interval = 1
#format = " $icon $barchart $utilization $frequency "
format_alt = " $icon $barchart $frequency{ $boost|} "
[[block.click]]
button = "right"
cmd = "gnome-system-monitor"

[[block]]
block =  "music"
format = " $icon {$combo.str(max_w:15,rot_interval:0.5) $play |} "
#[[block.click]]
#button = "right"
#cmd = "firefox 192.168.1.21:6680/iris"

[[block]]
block = "external_ip"
use_ipv4 = true
[[block.click]]
button = "right"
cmd = "gnome-terminal -- /opt/MullvadVPN/mullvad-gui --enable-crashpad"

[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 200
headphones_indicator = true
[[block.click]]
button = "left"
action = "toggle_mute"
[[block.click]]
button = "right"
cmd = "pavucontrol"

[[block]]
block = "toggle"
format = " $icon HDMI "
command_state = "xrandr | grep ' connected ' | grep -v eDP-1"
command_on  = "~/.screenlayout/dualscreen.sh"
command_off = "~/.screenlayout/laptop.sh"
interval = 5
[[block.click]]
button = "right"
cmd = "arandr"

#[[block]]
#block = "xrandr"
#format = " $brightness_icon $brightness"

[[block]]
block = "backlight"
device = "intel_backlight"
cycle = [0, 10, 50, 100]
[[block.click]]
button = "right"
cmd = "arandr"

[[block]]
block = "battery"
[[block.click]]
button = "right"
cmd = "gnome-power-statistics"

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/Brax?lang=fr&format=3' -s)"
interval = 600
[[block.click]]
button = "left"
update = true

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R', l:fr_FR) "
[[block.click]]
button = "right"
cmd = "gnome-control-center"

[[block]]
block = "tea_timer"
done_cmd = "notify-send 'Timer Finished'"
