theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {percentage} used"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
#format = "{icon} {used}/{total} ({available} free)"
format = "{icon} {available} free"
icons_format = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
#format = "{barchart} {utilization} {frequency}"
format = "{utilization}"
on_click = "gnome-system-monitor"

[[block]]
block =  "music"
buttons = ["play", "next"]
max_width = 15
#hide_when_empty = true
on_click = "firefox 192.168.1.21:6680/iris"

[[block]]
block = "external_ip"
format = "{country_flag} {ip}"
on_click = "gnome-terminal -- /opt/MullvadVPN/mullvad-gui --enable-crashpad"

#[[block]]
#block = "net"
#device = "wlp4s0"
#format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
#interval = 5
#hide_inactive = true

[[block]]
block = "networkmanager"
on_click = "gnome-terminal -- nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "wg-mullvad", "tun0"]
interface_name_include = []
ap_format = "{ssid^10}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"
on_click = "arandr"

#[[block]]
#bock = "toggle"
#text = "xrandr"
#command_state = "xrandr | grep HDMI-1\\ connected8 | grep -v eDP1"
#command_on = "~/.screenlayout/double_screen.sh"
#command_off = "~/.screenlayout/laptop.sh"
#icon_on = ""
#icon_off = ""
#interval = 5

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
on_click = "gnome-power-statistics"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
on_click = "gnome-control-center"

