[theme]
name = "solarized-dark"
#name = "slick"
[theme.overrides]
#separator = " ◀"
separator_fg = "#000000"
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
name = "awesome"
[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "


[[block]]
block = "toggle"
text = "HDMI"
command_state = "xrandr | grep HDMI-0\\ connected\\ 19 | grep -v eDP1"
command_on = "xrandr --output HDMI-0 --auto --left-of eDP-1-1"
command_off = "xrandr --output HDMI-0 --off --output eDP-1-1 --auto"

[[block]]
block = "xrandr"
icons = true
resolution = false
interval = 2

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
show = "percentage"

