[theme]
name = "solarized-dark"
#name = "slick"
[theme.overrides]
#separator = " ◀"
separator_fg = "#000000"
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
name = "awesome"
[icons.overrides]

[[block]]
block = "todo"
warning = 8
format = "{size} - ({number}) '{text}'"
filename = "~/Documents/todo.txt"
#interval = 1

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = true
graph_up = true
speed_down = true
graph_down = true
interval = 5
on_click = "xterm -e nmtui"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

