[theme]
#name = "solarized-dark"
name = "slick"
[theme.overrides]
separator_fg = "#000000"
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
name = "awesome"
[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = true
graph_up = true
speed_down = true
graph_down = true
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

