---
local:
  packages:
    - aha
    - ansible
    - ansible-lint
    - ca-certificates
    - curl
    - debian-archive-keyring
    - devscripts
    - fonts-font-awesome
    - fonts-powerline
    - gtk-chtheme
    - graphviz
    - iftop
    - jq
    - libdistro-info-perl
    - libfuse2
    - libssl-dev
    - lxappearance
    - ncdu
    - network-manager-openvpn-gnome
    - openvpn
    - pavucontrol
    - shellcheck
    - tldr
    - traceroute
    - tree
    - vlc
    - watch
    - wget
    - yamllint
    - youtube-dl
