---
- name: Create ~/.bin
  file: dest="{{ ansible_env.HOME }}/.bin" state=directory

- name: Link executables
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.bin/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./bin/*

- name: Find all dotfiles to symlink
  ansible.builtin.find:
    paths: "{{ role_path }}/files/dotfiles"
    file_type: any
  register: dot_files

- name: Symlink dotfiles files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.{{ item.path | basename }}"
    state: link
  with_items: "{{ dot_files.files }}"

- name: Find all .config files to symlink
  ansible.builtin.find:
    paths: "{{ role_path }}/files/config"
    file_type: any
  register: config_files

- name: Symlink config files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item.path | basename }}"
    state: link
  with_items: "{{ config_files.files }}"
