---
- name: Install git with apt
  become: true
  ansible.builtin.apt:
    name:
      - git
      - git-extras
    state: latest
    # update_cache: true
  when: ansible_os_family == "Debian"

- name: Install git with yum
  become: true
  ansible.builtin.yum:
    name:
      - git
      - git-extras
    state: latest
    # update_cache: true
  when: ansible_os_family == "RedHat"
