---
# Installation
- import_tasks: installer.yml

- name: Symlink conf files
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item | basename }}"
    state: link
  with_fileglob:
    - ./*
