---
# Installation
- import_tasks: installer.yml

# Plugin manager
- name: vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
  tags: update

# Configuration
- name: Find all files to symlink
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: any
  register: vim_files

- name: Symlink conf files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.vim/{{ item.path | basename }}"
    state: link
  with_items: "{{ vim_files.files }}"

- name: Install plugins
  command: vim +PluginInstall +qall
