---
# Installation
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

# Plugin manager
- name: vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: "~/.vim/bundle/Vundle.vim"
  tags: update

# Configuration
- name: Find all files to symlink
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: any
  register: vim_files

- name: Symlink conf files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/.vim/{{ item.path | basename }}"
    state: link
  with_items: "{{ vim_files.files }}"

- name: Install plugins
  command: vim +PluginInstall +qall
  when: vim_install_plugins|bool
